# Generated by Django 6.0.2 on 2026-02-17 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='cards/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='cards/back/')),
                ('front_text', models.CharField(blank=True, default='', max_length=255)),
                ('back_text', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='cards', to='cards.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=140)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='cards.card')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relations', to=settings.AUTH_USER_MODEL)),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='cards.card')),
            ],
            options={
                'unique_together': {('owner', 'from_card', 'to_card')},
            },
        ),
    ]
